name = "icra-engineer-v1"
main = "src/worker.ts"
compatibility_date = "2026-06-01"
workers_dev = false

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[routes]]
pattern = "icra.engineer"
custom_domain = true

[[routes]]
pattern = "www.icra.engineer"
custom_domain = true

[vars]
SITE_URL = "https://icra.engineer"
